version: "3.9"

services:
  db:
    image: postgres:16
    container_name: staffly-db
    environment:
      POSTGRES_DB: staffly
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
    container_name: staffly-backend
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/staffly
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app

      JWT_SECRET: dev-very-secret-key-change-me-32+chars-long!!_0123456789
      ACCESS_TTL_MINUTES: 15
      REFRESH_TTL_DAYS: 30

      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      VAPID_SUBJECT: ${VAPID_SUBJECT}

      # ✅ S3 (Yandex Object Storage)
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_REGION: ${S3_REGION}
      S3_PUBLIC_BASE_URL: ${S3_PUBLIC_BASE_URL}
      S3_PUBLIC_BUCKET: ${S3_PUBLIC_BUCKET}
      S3_PRIVATE_BUCKET: ${S3_PRIVATE_BUCKET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}

    ports:
      - "8080:8080"
    depends_on:
      - db

  backend-worker:
    build:
      context: ../backend
    container_name: staffly-backend-worker
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev,worker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/staffly
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app

      JWT_SECRET: dev-very-secret-key-change-me-32+chars-long!!_0123456789
      ACCESS_TTL_MINUTES: 15
      REFRESH_TTL_DAYS: 30

      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      VAPID_SUBJECT: ${VAPID_SUBJECT}

      # ✅ S3 (Yandex Object Storage)
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_REGION: ${S3_REGION}
      S3_PUBLIC_BASE_URL: ${S3_PUBLIC_BASE_URL}
      S3_PUBLIC_BUCKET: ${S3_PUBLIC_BUCKET}
      S3_PRIVATE_BUCKET: ${S3_PRIVATE_BUCKET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}

    depends_on:
      - db
    command: ["java","-jar","/app/app.jar","--spring.profiles.active=dev,worker"]

volumes:
  pgdata:
