version: "3.9"

services:
  db:
    image: postgres:16
    container_name: staffly-db
    environment:
      POSTGRES_DB: staffly
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
    container_name: staffly-backend
    environment:
      SPRING_PROFILES_ACTIVE: prod

      # DB
      DB_URL: jdbc:postgresql://db:5432/staffly
      DB_USER: app
      DB_PASSWORD: app

      # JWT secret (in prod обязательно свой)
      JWT_SECRET: prod-very-secret-key-change-me-32+chars-long!!_0123456789

      ACCESS_TTL_MINUTES: 15
      REFRESH_TTL_DAYS: 30

      # Public URL (optional)
      PUBLIC_BASE_URL: http://staffly.store
    depends_on:
      - db
    volumes:
      - avatars:/app/data/avatars

  frontend:
    build:
      context: ../frontend/staffly-frontend
    container_name: staffly-frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  pgdata:
  avatars: