version: "3.9"

services:
  db:
    image: postgres:16
    container_name: staffly-db
    environment:
      POSTGRES_DB: staffly
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
    container_name: staffly-backend

    env_file:
      - .env

    environment:
      SPRING_PROFILES_ACTIVE: prod

      # DB
      DB_URL: jdbc:postgresql://db:5432/staffly
      DB_USER: app
      DB_PASSWORD: app

      # JWT secret (in prod обязательно свой)
      JWT_SECRET: prod-very-secret-key-change-me-32+chars-long!!_0123456789

      ACCESS_TTL_MINUTES: 15
      REFRESH_TTL_DAYS: 30

      # Public URL (optional)
      PUBLIC_BASE_URL: https://staffly.store

      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      VAPID_SUBJECT: ${VAPID_SUBJECT}

    depends_on:
      - db
    volumes:
      - avatars:/app/data/avatars
      - training:/app/data/training

  backend-worker:
    build:
      context: ../backend
    container_name: staffly-backend-worker
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod,worker
      DB_URL: jdbc:postgresql://db:5432/staffly
      DB_USER: app
      DB_PASSWORD: app
      JWT_SECRET: prod-very-secret-key-change-me-32+chars-long!!_0123456789
      ACCESS_TTL_MINUTES: 15
      REFRESH_TTL_DAYS: 30
      PUBLIC_BASE_URL: https://staffly.store
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      VAPID_SUBJECT: ${VAPID_SUBJECT}
    depends_on:
      - db
    volumes:
      - avatars:/app/data/avatars
      - training:/app/data/training
    command: ["java","-jar","/app/app.jar","--spring.profiles.active=prod,worker"]

  frontend:
    build:
      context: ../frontend/staffly-frontend
    container_name: staffly-frontend
    depends_on:
      - backend
    # ВАЖНО: наружу порт больше не публикуем — это делает Caddy
    # ports:
    #   - "80:80"

  caddy:
    image: caddy:2
    container_name: staffly-caddy
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  pgdata:
  avatars:
  training:
  caddy_data:
  caddy_config:
