spring:
  datasource:
    url: jdbc:postgresql://db:5432/staffly
    username: app
    password: app

app:
  s3:
    public-bucket: ${S3_PUBLIC_BUCKET:staffly-prod}
    private-bucket: ${S3_PRIVATE_BUCKET:staffly-private}

logging:
  level:
    ru.staffly: INFO
